export const roleAccessRules: Record<string, string[]> = {
  admin: [],
  manager: ["/billing", "/general-settings"],
  accountant: [
    "/general-settings",
    "/drivers",
    "/customers",
    "/contractors",
    "/vehicles",
    "/vehicle-types",
    "/services-vehicle-price",
  ],
  customer: [
    "/billing",
    "/drivers",
    "/customers",
    "/contractors",
    "/vehicles",
    "/vehicle-types",
    "/general-settings",
    "/services-vehicle-price",
    "/jobs/manage",
  ],
  driver: [
    "/billing",
    "/drivers",
    "/customers",
    "/contractors",
    "/vehicles",
    "/vehicle-types",
    "/general-settings",
    "/services-vehicle-price",
    "/jobs/new",
    "/jobs/bulk-upload",
    "/jobs/manage",
  ],
};
